### ISSUE TITLE
N-Queens in JavaScript

### ISSUE THREAD

**Issue by pradeexsu** [metoop/Cache-Algorithms#10]
### N-Queens
```
The n-queens puzzle is the problem of placing n queens on an n×n chessboard such that no two queens attack each other.

Given an integer n, return all distinct solutions to the n-queens puzzle.
```
![8-queens](https://user-images.githubusercontent.com/49487927/95110338-803f9100-075b-11eb-9dd8-a5806e1fc6f6.png)
```
Each solution contains a distinct board configuration of the n-queens' placement, where 'Q' and '.' both indicate a queen and an empty space respectively.
```
### Example:
Input: 4
```Output: 

[
 [".Q..",  // Solution 1
  "...Q",
  "Q...",
  "..Q."],

 ["..Q.",  // Solution 2
  "Q...",
  "...Q",
  ".Q.."]
]
```

### Explanation: 
There exist two distinct solutions to the 4-queens puzzle as shown above.

**Note: Read [README](https://github.com/metoop/Cache-Algorithms/blob/main/README.md) carefully.**
**your PR accepted if only if your code passes all the test case of [n-Queen](https://leetcode.com/problems/n-queens/) problem on leetcode.**

**Comment by sultansingh731** [comment]
can i work on this project
