### ISSUE TITLE
Implement Trie (Prefix Tree) in JavaScript

### ISSUE THREAD

**Issue by pradeexsu** [metoop/Cache-Algorithms#13]
Implement a trie with insert, search, and startsWith methods.

### Example:
```Trie trie = new Trie();

trie.insert("apple");
trie.search("apple");   // returns true
trie.search("app");     // returns false
trie.startsWith("app"); // returns true
trie.insert("app");   
trie.search("app");     // returns true
```
### Note:
```
    You may assume that all inputs are consist of lowercase letters a-z.
    All inputs are guaranteed to be non-empty strings.
```

**Note: Read [README](https://github.com/metoop/Cache-Algorithms/blob/main/README.md) carefully.**
**your PR accepted if only if your code passes all the test case of [ Implement Trie (Prefix Tree) ](https://leetcode.com/problems/implement-trie-prefix-tree/) problem on leetcode.**

**Comment by sultansingh731** [comment]
can I work on this issue sir
